# Generated by Django 5.0.6 on 2024-05-20 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0003_rename_created_at_wishlist_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist_item",
            name="wishlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="wishlist.wishlist",
            ),
        ),
    ]
