# Generated by Django 5.0.6 on 2024-05-21 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0004_alter_wishlist_item_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist_item",
            name="wishlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wishlist.wishlist"
            ),
        ),
    ]
