# Generated by Django 5.0.4 on 2024-04-22 11:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='maxsulot nomi')),
                ('slug', models.SlugField(help_text='Slug for the category', unique=True)),
                ('description', models.TextField(verbose_name='Description nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('image', models.ImageField(upload_to='product/product_image')),
                ('stock', models.IntegerField(default=0, help_text='Mahsulot chegirma miqdorini kiriting.', validators=[django.core.validators.MinValueValidator(0, message="Sotish mikdori 0 yoki undan katta bo'lishi kerak."), django.core.validators.MaxValueValidator(100, message="Sotish mikdori 100 yoki undan kam bo'lishi kerak.")], verbose_name='Sotish Mikdori')),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Category nomi')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['name'],
            },
        ),
    ]
