# Generated by Django 5.0.4 on 2024-04-27 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_options_product_true_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='chegirma',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message="Satish mikdori 0 yoki undan katta bo'lishi kerak."), django.core.validators.MaxValueValidator(100, message="Sotish mikdori 100 yoki undan kam bo'lishi kerak.")]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(help_text='Maxsulot soni', verbose_name='Sotish Mikdori'),
        ),
    ]
