# Generated by Django 5.0.6 on 2024-05-11 09:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0008_initial'),
        ('store', '0006_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Maxsulot nomi')),
                ('slug', models.SlugField(help_text='Slug for the category', unique=True)),
                ('description', models.TextField(verbose_name='Description nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('image', models.ImageField(upload_to='prod_image/product_image')),
                ('chegirma', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, message="Satish mikdori 0 yoki undan katta bo'lishi kerak."), django.core.validators.MaxValueValidator(100, message="Sotish mikdori 100 yoki undan kam bo'lishi kerak.")])),
                ('stock', models.IntegerField(help_text='Maxsulot soni', verbose_name='Sotish Mikdori')),
                ('true_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Haqiqiy narx')),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Category nomi')),
            ],
        ),
    ]
