# Generated by Django 5.0.6 on 2024-05-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='chegirma',
            new_name='discount',
        ),
    ]
