# Generated by Django 5.0.6 on 2024-06-08 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0011_ulchmlar"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ulchmlar",
        ),
    ]
