# Generated by Django 5.0.4 on 2024-04-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
