# Generated by Django 5.0.4 on 2024-04-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None, help_text='Slug for the category', unique=True),
            preserve_default=False,
        ),
    ]
