# Generated by Django 5.0.6 on 2024-05-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0007_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Category nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descriptions nomi')),
                ('image', models.ImageField(blank=True, upload_to='category_images')),
                ('slug', models.SlugField(help_text='Slug for the category', unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
    ]
