# Generated by Django 5.0.6 on 2024-06-08 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0012_delete_ulchmlar"),
        ("ulcham_uchun", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Ulchmlar",
            new_name="Ulchamlar",
        ),
    ]
