# Generated by Django 5.0.6 on 2024-05-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
    ]
