# Generated by Django 5.0.6 on 2024-05-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_date'], 'verbose_name': 'cart item', 'verbose_name_plural': 'cart items'},
        ),
    ]
